### ISSUE TITLE
Consider including vmware-api-session-id as a parameter

### ISSUE THREAD

**Issue by jachinte** [vmware/vmware-openapi-generator#44]
Hi,

Since the API expects the session id as a request header, I was wondering if parameter "vmware-api-session-id" should be included in the generated specification.

I am currently generating code based on the generated files and it would be great having this parameter there.

Thanks,
Miguel

**Comment by jachinte** [comment]
An example of this would be listing all the VMs:
```bash
curl -sik -H 'vmware-api-session-id: <the-session-id>' -X GET https://<id-address>/rest/vcenter/vm
```

Failing to provide that parameter would end up in an unauthenticated request (401).

**Comment by sreeshas** [comment]
@VamshikShetty  can you take a look at this?

**Comment by kunal-pmj** [comment]
Hi @jachinte 

We are working on a fix. Will update you soon

Thanks
Kunal

**Comment by kunal-pmj** [comment]
Hi @jachinte 

The issue has been fixed with following [change](https://github.com/vmware/vmware-openapi-generator/pull/47). We are closing this issue.

Thanks
Kunal
