### ISSUE TITLE
Definition names in generated swagger file has dot (.) in them.

### ISSUE THREAD

**Issue by shubhamyelekar** [vmware/vmware-openapi-generator#50]
I am trying to do the following things:
1. Generate swagger json by providing the VC ip to vmware-openapi-generator.
2. Use the json to autogenerate the TypeScript code that will be used to call the APIs.

In the generated json , many of the definition names have dot in them. For ex:
`definitions:
  appliance.access.consolecli_result:
    type: object 
    properties:
      value:
        type: boolean
    required:
      - value `

When I try to generate the corresponding class in Typescript for `appliance.access.consolecli_result`
The generated class in TypeScript will have dot in them which is syntactically wrong. Someother delimiter (like camelcasing )other  than than dot can be used here  in the json.

**Comment by kunal-pmj** [comment]
Handling the special characters is responsibility of the code generators. 

. in model names is not prohibited by swagger parsers/validators. 

closing the issue
